theme: jekyll-theme-minimal
logo: /docs/assets/images/logo.png
show_downloads: true
google_analytics: G-KC8KPWLNCW
authors:
  - name: ila
    url: https://github.com/ila-embsys
  - name: MrDimLis
    url: https://github.com/mrdimfox
github:
  msi_url: https://github.com/ila-embsys/justrunmydebugger/releases/download/v0.1.0/justrunmydebugger_0.1.0_x64.msi
  deb_url: https://github.com/ila-embsys/justrunmydebugger/releases/download/v0.1.0/justrunmydebugger_0.1.0_amd64.deb
  appimage_url: https://github.com/ila-embsys/justrunmydebugger/releases/download/v0.1.0/justrunmydebugger_0.1.0_amd64.AppImage
